# DB
DB_PASSWORD = 'DB_PASSWORD'

# plaid
PLAID_CLIENT_ID = 'PLAID_CLIENT_ID'
PLAID_PUBLIC_KEY = 'PLAID_PUBLIC_KEY'
PLAID_SECRET = 'PLAID_SECRET'
PLAID_ENV = 'PLAID_ENV'

# Auth0
AUTH0_CLIENT_ID = 'AUTH0_CLIENT_ID'
AUTH0_CLIENT_SECRET = 'AUTH0_CLIENT_SECRET'
AUTH0_CALLBACK_URL = 'AUTH0_CALLBACK_URL'
AUTH0_DOMAIN = 'AUTH0_DOMAIN'
AUTH0_AUDIENCE = 'AUTH0_AUDIENCE'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'
